// Login Action Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

// Form Action Types
export const SET_ADDITIONAL_INFO = 'SET_ADDITIONAL_INFO';
export const SET_BANK_ACCOUNT_DETAILS = 'SET_BANK_ACCOUNT_DETAILS';
export const SET_INITIATE_PLEDGE = 'SET_INITIATE_PLEDGE';
export const SET_STEP_PROGRESS = 'SET_STEP_PROGRESS';
export const RESET_FORMS = 'RESET_FORMS';
export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const SET_FORM_ERRORS = 'SET_FORM_ERRORS';
export const CLEAR_FORM_ERRORS = 'CLEAR_FORM_ERRORS';
